SpeedOS.LoadAPI("SpeedAPI/buffering")
buffering.setBackgroundColor(colors.white)
term.clear()
buffering.setTextColor(colors.black)
buffering.setCursorPos(1, 1)
term.write("Hello, World!")
buffering.setCursorPos(1, 2)
print("Background Color: "..buffering.backgroundColor)
print("Text Color: "..buffering.textColor)
